# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "gomod"
    directories:
      - "/"
      - "/examples/application-patterns"
      - "/examples/brand-site"
      - "/examples/getting-started"
      - "/site"
    schedule:
      interval: "weekly"
    groups:
      go-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      go-major:
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: "docker"
    directories:
      - "/"
      - "/site/tests/e2e"
    schedule:
      interval: "weekly"
    groups:
      container-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      container-major:
        patterns: ["*"]
        update-types: ["major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions:
        patterns: ["*"]
