// Command vendorgen generates assets/vendor_gen.go from the vendor version
// manifest (assets/js/vendor/versions.json) — the single source of truth for
// every vendored third-party JS dependency's version, file, and origin.
//
// Modes:
//
//	go run ./scripts/vendorgen            // generate vendor_gen.go + verify files exist
//	go run ./scripts/vendorgen -check     // CI: fail if regeneration would change the file
//	go run ./scripts/vendorgen -download  // fetch pinned versions from the manifest, then generate
//
// Run from the repo root. CI fails if the committed vendor_gen.go is stale.
package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
)

const (
	manifestPath = "assets/js/vendor/versions.json"
	outPath      = "assets/vendor_gen.go"
	vendorRoot   = "assets/js/vendor"
)

// dep is one entry in versions.json.
type dep struct {
	Version string `json:"version"`
	File    string `json:"file"`
	URL     string `json:"url"`
}

// constName maps a manifest module key to its exported Go constant name.
// Adding a new dep requires adding it here — intentional friction.
var constName = map[string]string{
	"alpinejs":          "AlpineJSURL",
	"alpinejs-collapse": "AlpineCollapseURL",
	"alpinejs-focus":    "AlpineFocusURL",
	"htmx.org":          "HTMXURL",
	"htmx-ext-sse":      "HTMXExtSSEURL",
	"htmx-ext-ws":       "HTMXExtWSURL",
}

func urlPath(module string, d dep) string {
	return "/assets/js/vendor/" + module + "/" + d.Version + "/" + d.File
}

func diskPath(module string, d dep) string {
	return filepath.Join(vendorRoot, module, d.Version, d.File)
}

func loadManifest() (map[string]dep, error) {
	b, err := os.ReadFile(manifestPath)
	if err != nil {
		return nil, err
	}
	var m map[string]dep
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, fmt.Errorf("parse %s: %w", manifestPath, err)
	}
	return m, nil
}

// render produces the formatted vendor_gen.go source for the given manifest.
func render(deps map[string]dep) string {
	type kv struct {
		name, url string
	}
	var rows []kv
	for module, d := range deps {
		name := constName[module]
		if name == "" {
			panic("vendorgen: no constName for module " + module)
		}
		rows = append(rows, kv{name, urlPath(module, d)})
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].name < rows[j].name })

	var buf bytes.Buffer
	buf.WriteString("// Code generated by vendorgen. DO NOT EDIT.\n")
	buf.WriteString("// Source of truth: assets/js/vendor/versions.json\n\n")
	buf.WriteString("package assets\n\n")
	buf.WriteString("const (\n")
	for _, r := range rows {
		fmt.Fprintf(&buf, "\t%s = %q\n", r.name, r.url)
	}
	buf.WriteString(")\n")

	out, err := format.Source(buf.Bytes())
	if err != nil {
		panic(fmt.Sprintf("vendorgen: gofmt failed: %v\n%s", err, buf.String()))
	}
	return string(out)
}

func verifyFilesExist(deps map[string]dep) error {
	for module, d := range deps {
		p := diskPath(module, d)
		if _, err := os.Stat(p); err != nil {
			return fmt.Errorf("vendored file missing: %s (run `just vendor-js`): %w", p, err)
		}
	}
	return nil
}

func main() {
	check := flag.Bool("check", false, "fail if vendor_gen.go would change")
	download := flag.Bool("download", false, "download pinned versions from the manifest")
	flag.Parse()

	deps, err := loadManifest()
	if err != nil {
		fmt.Fprintln(os.Stderr, "vendorgen:", err)
		os.Exit(1)
	}

	if *download {
		if err := downloadAll(deps); err != nil { // defined in download.go (Task 8)
			fmt.Fprintln(os.Stderr, "vendorgen download:", err)
			os.Exit(1)
		}
	}

	if err := verifyFilesExist(deps); err != nil {
		fmt.Fprintln(os.Stderr, "vendorgen:", err)
		os.Exit(1)
	}

	gen := render(deps)

	if *check {
		existing, err := os.ReadFile(outPath)
		if err != nil || string(existing) != gen {
			fmt.Fprintf(os.Stderr, "::error::%s is stale — run `go run ./scripts/vendorgen` and commit\n", outPath)
			os.Exit(1)
		}
		return
	}

	if err := os.WriteFile(outPath, []byte(gen), 0o644); err != nil {
		fmt.Fprintln(os.Stderr, "vendorgen:", err)
		os.Exit(1)
	}
	fmt.Printf("vendorgen: wrote %s (%d deps)\n", outPath, len(deps))
}
