// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package components

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	rootcomponents "github.com/araihu/goshtoso/components"
	"github.com/araihu/goshtoso/components/radio"
	"github.com/araihu/goshtoso/site/internal/pages/demo"
)

var radioAPISections = []demo.APISection{
	demo.StructAPI[radio.Config](
		rootcomponents.KindRadio,
		"Config",
		"radio.Radio(cfg Config) Instance",
		"Configures one native radio input, including optional container, segmented, HTMX, and Alpine behavior.",
		[]demo.APIPropDoc{
			{Name: "ID", Default: `""`, Description: "Native input ID and label for target; supply a unique value for an associated label."},
			{Name: "Name", Default: `""`, Description: "Native form-field name shared by mutually exclusive radios."},
			{Name: "Value", Default: `""`, Description: "Value submitted when this radio is selected."},
			{Name: "Label", Default: `""`, Description: "Visible option label."},
			{Name: "Checked", Default: "false", Description: "Sets the initial native checked state."},
			{Name: "Disabled", Default: "false", Description: "Adds the native disabled attribute."},
			{Name: "Tone", Default: "TonePrimary", Allowed: []string{"TonePrimary", "ToneSecondary", "ToneInfo", "ToneSuccess", "ToneWarning", "ToneDanger"}, Description: "Sets checked and focus colors, including segmented selection colors."},
			{Name: "Size", Default: "SizeMD", Allowed: []string{"SizeSM", "SizeMD", "SizeLG", "SizeXL"}, Description: "Sets the native radio size; segmented mode uses its own pill dimensions."},
			{Name: "HelperText", Default: `""`, Description: "Non-empty text selects the description layout unless Segmented is true."},
			{Name: "HelperTextID", Default: `"" (helper has no ID)`, Description: "Normal standalone Radio with non-empty HelperText renders aria-describedby on the input and the matching helper span ID. Segmented Radio takes precedence and renders neither the typed aria-describedby attribute nor a helper span. RadioGroup renders aria-describedby on the input but does not give its helper span a matching ID."},
			{Name: "BadgeColor", Default: `"" (plain group label)`, Allowed: []string{"success", "danger", "warning", "info", "neutral", "primary", "secondary"}, Description: "Applies badge styling only to RadioGroup items that also have HelperText."},
			{Name: "Container", Default: "false", Description: "Selects the bordered wrapper for a non-segmented standalone Radio. Segmented Radio ignores it. RadioGroup ignores the wrapper layout, but Container still changes the grouped item's inner input background through shared input classes."},
			{Name: "Segmented", Default: "false", Description: "Selects the standalone segmented-pill renderer, intended for RadioBar; RadioGroup ignores it and renders its own standard item path."},
			{Name: "RootClass", Default: `""`, Description: "Appends CSS classes to a standalone Radio root; RadioGroup ignores it."},
			{Name: "HTMX", Default: "nil (no HTMX attributes)", Description: "Optional server-interaction attributes applied to the input."},
			{Name: "Alpine", Default: "nil (no Alpine directives)", Description: "Optional client-side directives applied to the input."},
			{Name: "InputAttrs", Default: "nil", Description: "Additional non-conflicting attributes appended to the native input. Conflicts with modeled keys create duplicate attributes rather than overriding them; use typed fields for name, value, disabled, checked, HTMX, and Alpine behavior."},
		},
	),
	demo.StructAPI[radio.GroupConfig](
		rootcomponents.KindRadioGroup,
		"GroupConfig",
		"radio.RadioGroup(cfg GroupConfig) GroupInstance",
		"Configures a bordered list of radio options.",
		[]demo.APIPropDoc{
			{Name: "Title", Default: `"" (omitted)`, Description: "Optional heading rendered above the group."},
			{Name: "Items", Default: "nil (empty group)", Description: "Radio configurations rendered in order.", Required: true},
		},
	),
	demo.StructAPI[radio.HTMXConfig](
		"",
		"HTMXConfig",
		"",
		"Maps HTMX request, swap, and submission attributes onto a radio input.",
		[]demo.APIPropDoc{
			{Name: "Get", Default: `"" (omitted)`, Description: "GET request URL."},
			{Name: "Post", Default: `"" (omitted)`, Description: "POST request URL."},
			{Name: "Put", Default: `"" (omitted)`, Description: "PUT request URL."},
			{Name: "Delete", Default: `"" (omitted)`, Description: "DELETE request URL."},
			{Name: "Patch", Default: `"" (omitted)`, Description: "PATCH request URL."},
			{Name: "Target", Default: `"" (HTMX default target)`, Description: "CSS selector rendered as hx-target."},
			{Name: "Swap", Default: `"" (HTMX default swap)`, Description: "Swap strategy rendered as hx-swap."},
			{Name: "Trigger", Default: `"change" when a verb is set; otherwise omitted`, Description: "Explicit trigger override, or the radio-native change event synthesized for requests."},
			{Name: "Indicator", Default: `"" (omitted)`, Description: "CSS selector rendered as hx-indicator."},
			{Name: "PushURL", Default: "false", Description: "When true, renders hx-push-url=\"true\"."},
			{Name: "Confirm", Default: `"" (omitted)`, Description: "Confirmation message rendered as hx-confirm."},
			{Name: "Vals", Default: `"" (omitted)`, Description: "Caller-provided hx-vals JSON expression."},
			{Name: "Include", Default: `"" (omitted)`, Description: "CSS selector rendered as hx-include."},
		},
	),
	demo.StructAPI[radio.AlpineConfig](
		"",
		"AlpineConfig",
		"",
		"Maps optional Alpine.js directives onto a radio input.",
		[]demo.APIPropDoc{
			{Name: "Data", Default: `"" (omitted)`, Description: "Expression rendered as x-data."},
			{Name: "Model", Default: `"" (omitted)`, Description: "Expression rendered as x-model."},
			{Name: "OnChange", Default: `"" (omitted)`, Description: "Expression rendered as x-on:change."},
			{Name: "BindChecked", Default: `"" (omitted)`, Description: "Expression rendered as x-bind:checked."},
			{Name: "BindDisabled", Default: `"" (omitted)`, Description: "Expression rendered as x-bind:disabled."},
		},
	),
	demo.FunctionsAPI(
		rootcomponents.KindRadioBar,
		"RadioBar",
		"",
		"Groups segmented Radio children in a connected bordered pill bar.",
		[]demo.APIPropDoc{
			{Name: "RadioBar", Signature: "func RadioBar() BarInstance", Default: "n/a", Description: "Creates the child-rendering segmented-control wrapper; children should set Config.Segmented."},
		},
	),
}

// RadioDemoPage renders the Radio component demo as a full document.
// Kept for direct invocation; the registry uses radioDemoContent directly.
func RadioDemoPage() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = demo.Layout("Radio", "radio", radioDemoContent()).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioDemoContent renders the demo. Each radio variant lives in its own preview
// frame followed by its own code block (mirrors penguinui.com/components/radio).
// The variant set stays wrapped in #radio-fragment so the e2e selectors keep working.
func radioDemoContent() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var2 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var2 == nil {
			templ_7745c5c3_Var2 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div id=\"radio-fragment\" x-data=\"{ selectedSize: 'md' }\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.ComponentDemo(
			demo.ComponentDemoProps{
				Title:       "Radio",
				Description: "Single-select form input. Supports color variants, sizes, descriptions, bordered containers, segmented pill bars, and first-class HTMX + Alpine.js interaction primitives.",
			},
			radioDefaultPreview(),
			`@radio.Radio(radio.Config{
    ID: "r-mac", Name: "os", Value: "mac", Label: "Mac", Checked: true,
})
@radio.Radio(radio.Config{
    ID: "r-win", Name: "os", Value: "windows", Label: "Windows",
})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.DemoSection(
			demo.DemoSectionProps{
				Title:       "With Container",
				Description: "Wraps each option in a bordered container with Container: true.",
			},
			radioContainerPreview(),
			`@radio.Radio(radio.Config{
    ID: "r-c-mac", Name: "os-c", Value: "mac", Label: "Mac",
    Container: true, Checked: true,
})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.DemoSection(
			demo.DemoSectionProps{
				Title:       "Segmented",
				Description: "A true segmented control (connected pill bar). Set Segmented: true and group inside RadioBar.",
			},
			radioSegmentedPreview(),
			`@radio.RadioBar() {
    @radio.Radio(radio.Config{ID: "r-seg-a", Name: "g", Value: "a", Label: "A", Segmented: true, Checked: true})
    @radio.Radio(radio.Config{ID: "r-seg-b", Name: "g", Value: "b", Label: "B", Segmented: true})
}`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.DemoSection(
			demo.DemoSectionProps{
				Title:       "With Description",
				Description: "Add helper text under the label via HelperText (wire HelperTextID for aria-describedby).",
			},
			radioDescriptionPreview(),
			`@radio.Radio(radio.Config{
    ID: "r-desc-mac", Name: "os-desc", Value: "mac", Label: "Mac",
    HelperText:   "For macOS Big Sur and higher.",
    HelperTextID: "r-desc-mac-desc",
    Checked:       true,
})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.DemoSection(
			demo.DemoSectionProps{
				Title:       "Color Variants",
				Description: "Six semantic colors via Tone: radio.TonePrimary, radio.ToneSecondary, radio.ToneInfo, radio.ToneSuccess, radio.ToneWarning, radio.ToneDanger.",
			},
			radioColorPreview(),
			`@radio.Radio(radio.Config{ID: "r-success", Name: "v", Value: "su", Label: "Success", Tone: radio.ToneSuccess, Checked: true})
@radio.Radio(radio.Config{ID: "r-danger", Name: "v2", Value: "d", Label: "Danger", Tone: radio.ToneDanger, Checked: true})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.DemoSection(
			demo.DemoSectionProps{
				Title:        "Sizes",
				Description:  "Four box sizes via Size: SizeSM, SizeMD (default), SizeLG, SizeXL.",
				AbovePreview: radioSizeSelector(),
			},
			radioSizesPreview(),
			`@radio.Radio(radio.Config{
    ID: "r-size-md", Name: "radio-size-preview", Value: "md",
    Label: "Medium", Size: radio.SizeMD, Checked: true,
})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.DemoSection(
			demo.DemoSectionProps{
				Title:       "Disabled",
				Description: "Disabled: true blocks interaction and dims the control.",
			},
			radioDisabledPreview(),
			`@radio.Radio(radio.Config{ID: "r-d1", Name: "dis", Value: "a", Label: "Disabled unchecked", Disabled: true})
@radio.Radio(radio.Config{ID: "r-d2", Name: "dis", Value: "b", Label: "Disabled checked", Disabled: true, Checked: true})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.DemoSection(
			demo.DemoSectionProps{
				Title:       "Alpine — client state",
				Description: "Wire AlpineConfig for client-only state. Clicks update local x-data without a server roundtrip.",
			},
			radioAlpinePreview(),
			`@radio.Radio(radio.Config{
    ID: "r-a-md", Name: "size-a", Value: "md", Label: "md", Segmented: true,
    Alpine: &radio.AlpineConfig{
        BindChecked: "selected === 'md'",
        OnChange:    "selected = 'md'",
    },
})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.DemoSection(
			demo.DemoSectionProps{
				Title:       "HTMX — server roundtrip",
				Description: "Wire HTMXConfig for a server roundtrip on change. The response swaps into the target.",
			},
			radioHTMXPreview(),
			`@radio.Radio(radio.Config{
    ID: "r-h-md", Name: "size-h", Value: "md", Label: "md", Segmented: true,
    HTMX: &radio.HTMXConfig{
        Get:    "/api/components/radio/echo?value=md",
        Target: "#radio-htmx-out",
        Swap:   "innerHTML",
    },
})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.DemoSection(
			demo.DemoSectionProps{
				Title:       "Hybrid — Alpine state + HTMX persistence",
				Description: "Set both Alpine and HTMX: a single click updates client state and fires the server roundtrip.",
			},
			radioHybridPreview(),
			`@radio.Radio(radio.Config{
    ID: "r-hy-md", Name: "size-hy", Value: "md", Label: "md", Segmented: true,
    Alpine: &radio.AlpineConfig{BindChecked: "selected === 'md'", OnChange: "selected = 'md'"},
    HTMX:   &radio.HTMXConfig{Get: "/api/components/radio/echo?value=md", Target: "#radio-hybrid-out", Swap: "innerHTML"},
})`,
		).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = demo.StructuredAPIReference(radioAPISections).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioDefaultPreview renders the default exclusive radio group.
func radioDefaultPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var3 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var3 == nil {
			templ_7745c5c3_Var3 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<div id=\"radio-default\" class=\"w-full max-w-md mx-auto\"><div class=\"flex flex-col gap-2\" data-testid=\"radio-default-group\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-d-mac", Name: "os-default", Value: "mac", Label: "Mac", Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-d-win", Name: "os-default", Value: "windows", Label: "Windows"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-d-linux", Name: "os-default", Value: "linux", Label: "Linux"}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioContainerPreview renders the bordered-container variant.
func radioContainerPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var4 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var4 == nil {
			templ_7745c5c3_Var4 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "<div id=\"radio-container\" class=\"w-full max-w-md mx-auto\"><div class=\"flex flex-wrap gap-2\" data-testid=\"radio-container-group\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-c-mac", Name: "os-container", Value: "mac", Label: "Mac", Container: true, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-c-win", Name: "os-container", Value: "windows", Label: "Windows", Container: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-c-linux", Name: "os-container", Value: "linux", Label: "Linux", Container: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 6, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioSegmentedPreview renders the connected pill-bar segmented variant.
func radioSegmentedPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var5 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var5 == nil {
			templ_7745c5c3_Var5 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 7, "<div id=\"radio-segmented\" class=\"w-full max-w-md mx-auto\"><div data-testid=\"radio-segmented-group\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var6 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-seg-mac", Name: "os-seg", Value: "mac", Label: "Mac", Segmented: true, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 8, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-seg-win", Name: "os-seg", Value: "windows", Label: "Windows", Segmented: true}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 9, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-seg-linux", Name: "os-seg", Value: "linux", Label: "Linux", Segmented: true}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = radio.RadioBar().Render(templ.WithChildren(ctx, templ_7745c5c3_Var6), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 10, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioDescriptionPreview renders radios with helper descriptions.
func radioDescriptionPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var7 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var7 == nil {
			templ_7745c5c3_Var7 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 11, "<div id=\"radio-description\" class=\"w-full max-w-md mx-auto\"><div class=\"flex flex-col gap-3\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{
			ID: "r-desc-mac", Name: "os-desc", Value: "mac", Label: "Mac",
			HelperText:   "For macOS Big Sur and higher.",
			HelperTextID: "r-desc-mac-desc",
			Checked:      true,
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{
			ID: "r-desc-win", Name: "os-desc", Value: "windows", Label: "Windows",
			HelperText:   "Windows 10 and Windows 11.",
			HelperTextID: "r-desc-win-desc",
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 12, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioColorPreview renders the six semantic color variants.
func radioColorPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var8 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var8 == nil {
			templ_7745c5c3_Var8 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 13, "<div id=\"radio-colors\" class=\"w-full max-w-2xl mx-auto\"><div class=\"flex flex-wrap gap-4\" data-testid=\"radio-color-variants\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-v-primary", Name: "v-primary", Value: "p", Label: "Primary", Tone: radio.TonePrimary, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-v-secondary", Name: "v-secondary", Value: "s", Label: "Secondary", Tone: radio.ToneSecondary, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-v-info", Name: "v-info", Value: "i", Label: "Info", Tone: radio.ToneInfo, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-v-success", Name: "v-success", Value: "su", Label: "Success", Tone: radio.ToneSuccess, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-v-warning", Name: "v-warning", Value: "w", Label: "Warning", Tone: radio.ToneWarning, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-v-danger", Name: "v-danger", Value: "d", Label: "Danger", Tone: radio.ToneDanger, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 14, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioSizeSelector renders the segmented size selector for the sizes preview.
func radioSizeSelector() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var9 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var9 == nil {
			templ_7745c5c3_Var9 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 15, "<div class=\"mb-3 flex items-center gap-4\"><label class=\"text-sm font-medium text-on-surface-strong dark:text-on-surface-dark-strong\">Size</label><div data-testid=\"radio-size-selector\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var10 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = radioSizeOption("sm", "sm").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 16, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radioSizeOption("md", "md").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 17, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radioSizeOption("lg", "lg").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 18, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radioSizeOption("xl", "xl").Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = radio.RadioBar().Render(templ.WithChildren(ctx, templ_7745c5c3_Var10), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 19, "</div><span class=\"sr-only\" data-testid=\"radio-size-selected\" x-text=\"selectedSize\"></span></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioSizeOption renders one segmented pill for the radio size selector.
func radioSizeOption(value, label string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var11 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var11 == nil {
			templ_7745c5c3_Var11 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = radio.Radio(radio.Config{
			ID:        "radio-size-selector-" + value,
			Name:      "radio-size-selector",
			Value:     value,
			Label:     label,
			Segmented: true,
			Alpine: &radio.AlpineConfig{
				BindChecked: "selectedSize === '" + value + "'",
				OnChange:    "selectedSize = '" + value + "'",
			},
		}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioSizesPreview renders a single radio at the selected input size.
func radioSizesPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var12 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var12 == nil {
			templ_7745c5c3_Var12 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 20, "<div id=\"radio-sizes\" class=\"w-full max-w-md mx-auto\"><div class=\"flex min-h-10 items-center justify-center\" data-testid=\"radio-sizes\"><div data-testid=\"radio-size-preview-sm\" x-show=\"selectedSize === 'sm'\" x-cloak>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-size-sm", Name: "radio-size-preview-sm", Value: "sm", Label: "Small", Size: radio.SizeSM, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 21, "</div><div data-testid=\"radio-size-preview-md\" x-show=\"selectedSize === 'md'\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-size-md", Name: "radio-size-preview-md", Value: "md", Label: "Medium", Size: radio.SizeMD, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 22, "</div><div data-testid=\"radio-size-preview-lg\" x-show=\"selectedSize === 'lg'\" x-cloak>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-size-lg", Name: "radio-size-preview-lg", Value: "lg", Label: "Large", Size: radio.SizeLG, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 23, "</div><div data-testid=\"radio-size-preview-xl\" x-show=\"selectedSize === 'xl'\" x-cloak>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-size-xl", Name: "radio-size-preview-xl", Value: "xl", Label: "XL", Size: radio.SizeXL, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 24, "</div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioDisabledPreview renders disabled radios.
func radioDisabledPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var13 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var13 == nil {
			templ_7745c5c3_Var13 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 25, "<div id=\"radio-disabled\" class=\"w-full max-w-md mx-auto\"><div class=\"flex flex-col gap-2\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-dis-1", Name: "dis", Value: "a", Label: "Disabled unchecked", Disabled: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-dis-2", Name: "dis", Value: "b", Label: "Disabled checked", Disabled: true, Checked: true}).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 26, "</div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioAlpinePreview renders the Alpine-only client-state showcase.
func radioAlpinePreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var14 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var14 == nil {
			templ_7745c5c3_Var14 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 27, "<div id=\"radio-alpine\" class=\"w-full max-w-md mx-auto\" x-data=\"{ selected: 'md' }\"><div class=\"mb-3\" data-testid=\"radio-alpine-group\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var15 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-a-sm", Name: "size-a", Value: "sm", Label: "sm", Segmented: true,
				Alpine: &radio.AlpineConfig{BindChecked: "selected === 'sm'", OnChange: "selected = 'sm'"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 28, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-a-md", Name: "size-a", Value: "md", Label: "md", Segmented: true,
				Alpine: &radio.AlpineConfig{BindChecked: "selected === 'md'", OnChange: "selected = 'md'"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 29, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-a-lg", Name: "size-a", Value: "lg", Label: "lg", Segmented: true,
				Alpine: &radio.AlpineConfig{BindChecked: "selected === 'lg'", OnChange: "selected = 'lg'"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = radio.RadioBar().Render(templ.WithChildren(ctx, templ_7745c5c3_Var15), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 30, "</div><div class=\"text-sm text-on-surface dark:text-on-surface-dark\" data-testid=\"radio-alpine-out\">Selected: <span x-text=\"selected\" class=\"font-mono font-semibold\"></span></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioHTMXPreview renders the HTMX-only server-roundtrip showcase.
func radioHTMXPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var16 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var16 == nil {
			templ_7745c5c3_Var16 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 31, "<div id=\"radio-htmx\" class=\"w-full max-w-md mx-auto\"><div class=\"mb-3\" data-testid=\"radio-htmx-group\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var17 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-h-sm", Name: "size-h", Value: "sm", Label: "sm", Segmented: true,
				HTMX: &radio.HTMXConfig{Get: "/api/components/radio/echo?value=sm", Target: "#radio-htmx-out", Swap: "innerHTML"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 32, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-h-md", Name: "size-h", Value: "md", Label: "md", Segmented: true,
				HTMX: &radio.HTMXConfig{Get: "/api/components/radio/echo?value=md", Target: "#radio-htmx-out", Swap: "innerHTML"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 33, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-h-lg", Name: "size-h", Value: "lg", Label: "lg", Segmented: true,
				HTMX: &radio.HTMXConfig{Get: "/api/components/radio/echo?value=lg", Target: "#radio-htmx-out", Swap: "innerHTML"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = radio.RadioBar().Render(templ.WithChildren(ctx, templ_7745c5c3_Var17), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 34, "</div><div id=\"radio-htmx-out\" class=\"text-sm text-on-surface dark:text-on-surface-dark\" data-testid=\"radio-htmx-out\"><span class=\"text-on-surface-muted dark:text-on-surface-dark-muted\">No selection yet.</span></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

// radioHybridPreview renders the hybrid Alpine-state + HTMX-persistence showcase.
func radioHybridPreview() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var18 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var18 == nil {
			templ_7745c5c3_Var18 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 35, "<div id=\"radio-hybrid\" class=\"w-full max-w-md mx-auto\" x-data=\"{ selected: 'md' }\"><div class=\"mb-3\" data-testid=\"radio-hybrid-group\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Var19 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-hy-sm", Name: "size-hy", Value: "sm", Label: "sm", Segmented: true,
				Alpine: &radio.AlpineConfig{BindChecked: "selected === 'sm'", OnChange: "selected = 'sm'"},
				HTMX:   &radio.HTMXConfig{Get: "/api/components/radio/echo?value=sm", Target: "#radio-hybrid-out", Swap: "innerHTML"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 36, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-hy-md", Name: "size-hy", Value: "md", Label: "md", Segmented: true,
				Alpine: &radio.AlpineConfig{BindChecked: "selected === 'md'", OnChange: "selected = 'md'"},
				HTMX:   &radio.HTMXConfig{Get: "/api/components/radio/echo?value=md", Target: "#radio-hybrid-out", Swap: "innerHTML"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 37, " ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = radio.Radio(radio.Config{ID: "r-hy-lg", Name: "size-hy", Value: "lg", Label: "lg", Segmented: true,
				Alpine: &radio.AlpineConfig{BindChecked: "selected === 'lg'", OnChange: "selected = 'lg'"},
				HTMX:   &radio.HTMXConfig{Get: "/api/components/radio/echo?value=lg", Target: "#radio-hybrid-out", Swap: "innerHTML"}}).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = radio.RadioBar().Render(templ.WithChildren(ctx, templ_7745c5c3_Var19), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 38, "</div><div class=\"text-sm text-on-surface dark:text-on-surface-dark space-y-1\"><div>Alpine: <span x-text=\"selected\" class=\"font-mono font-semibold\" data-testid=\"radio-hybrid-alpine-out\"></span></div><div id=\"radio-hybrid-out\" data-testid=\"radio-hybrid-htmx-out\"><span class=\"text-on-surface-muted dark:text-on-surface-dark-muted\">Server: not called yet.</span></div></div></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
